name: oboe
description: Oboe is a elegant state management library. Its description only needs two screenshots, Oboe not need Provider at root Widget, Oboe is tiny and ease use, only 2 API.
version: 0.1.1
homepage: https://github.com/ymzuiku/oboe

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #  entangle:
  #    path: /Users/pillar/work/darts/dart_entangle
  flutter:
    sdk: flutter
